import { z } from 'zod'

export const operatorRoleSchema = z.enum(['admin', 'dispatcher', 'customer-care', 'read-only'])

export const operatorActorSchema = z.object({
  id: z.string().min(1),
  role: operatorRoleSchema,
  demo: z.boolean(),
}).strict()

export const catalogStatusSchema = z.enum(['draft', 'validated', 'published', 'retired'])

/** Layout geometry of a template cell. Not a commercial fare class — see `seatClassSchema`. */
export const seatKindSchema = z.enum(['seat', 'double-bed', 'aisle', 'driver', 'blocked'])

/** Cell kinds a passenger can actually occupy; capacity is derived from these. */
export const sellableSeatKinds = ['seat', 'double-bed'] as const

/** Role a stop plays on a route. `both` means the route picks up and drops off there. */
export const stopRoleSchema = z.enum(['pickup', 'dropoff', 'both'])

export const branchSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
}).strict()

export const stopSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  branchId: z.string().min(1),
}).strict()

export const routeStopSchema = z.object({
  stopId: z.string().min(1),
  role: stopRoleSchema,
  sequence: z.number().int().nonnegative(),
  /** Minutes after route departure that the vehicle reaches this stop. */
  offsetMinutes: z.number().int().nonnegative().default(0),
}).strict()

export const routeSchema = z.object({
  id: z.string().min(1),
  origin: z.string().min(1),
  destination: z.string().min(1),
  stops: z.array(routeStopSchema),
}).strict()

/**
 * Commercial seat class (ghế ngồi, giường đơn, giường đôi, VIP…).
 * Price is the route fare scaled by `priceMultiplierBps`, where 10_000 = 1.0x.
 */
export const seatClassSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  priceMultiplierBps: z.number().int().min(1).max(1_000_000),
}).strict()

export const vehicleTemplateSeatSchema = z.object({
  code: z.string().regex(/^[A-Z][A-Z0-9]{0,5}$/u),
  floor: z.number().int().min(1).max(2),
  row: z.number().int().nonnegative(),
  column: z.number().int().nonnegative(),
  kind: seatKindSchema,
  /** Required for sellable kinds; null for aisle/driver/blocked cells. */
  seatClassId: z.string().min(1).nullable().default(null),
}).strict()

export const vehicleTemplateSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  floors: z.number().int().min(1).max(2),
  seats: z.array(vehicleTemplateSeatSchema),
}).strict()

export const vehicleSchema = z.object({
  id: z.string().min(1),
  label: z.string().min(1),
  templateId: z.string().min(1),
  active: z.boolean(),
}).strict()

export const fareRuleSchema = z.object({
  id: z.string().min(1),
  routeId: z.string().min(1),
  priceVnd: z.number().int().positive(),
  /** null applies the rule to every seat class on the route. */
  seatClassId: z.string().min(1).nullable().default(null),
  /** null bounds are open-ended; windows for one route/class pair must not overlap. */
  effectiveFrom: z.string().datetime().nullable().default(null),
  effectiveTo: z.string().datetime().nullable().default(null),
}).strict()

export const catalogTripSchema = z.object({
  id: z.string().min(1),
  routeId: z.string().min(1),
  vehicleId: z.string().min(1),
  departureAt: z.string().datetime(),
  arrivalAt: z.string().datetime(),
  fareId: z.string().min(1),
  /** Operator-stated capacity, cross-checked against the template. null skips the check. */
  declaredCapacity: z.number().int().positive().nullable().default(null),
  /** Set when the trip was generated by `expandSchedule`. */
  scheduleId: z.string().min(1).nullable().default(null),
}).strict()

/** Recurring departure pattern (lịch chạy) that expands into concrete trips. */
export const catalogScheduleSchema = z.object({
  id: z.string().min(1),
  routeId: z.string().min(1),
  vehicleId: z.string().min(1),
  fareId: z.string().min(1),
  /** ISO weekday numbers, 0 = Sunday. */
  weekdays: z.array(z.number().int().min(0).max(6)).min(1),
  /** UTC wall-clock departure, `HH:mm`. */
  departureTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/u),
  durationMinutes: z.number().int().positive(),
  activeFrom: z.string().datetime(),
  activeTo: z.string().datetime().nullable().default(null),
}).strict()

const catalogBody = {
  id: z.string().min(1),
  version: z.number().int().positive(),
  revision: z.number().int().nonnegative(),
  effectiveFrom: z.string().datetime(),
  branches: z.array(branchSchema),
  stops: z.array(stopSchema),
  routes: z.array(routeSchema),
  seatClasses: z.array(seatClassSchema).default([]),
  vehicleTemplates: z.array(vehicleTemplateSchema),
  vehicles: z.array(vehicleSchema),
  fares: z.array(fareRuleSchema),
  schedules: z.array(catalogScheduleSchema).default([]),
  trips: z.array(catalogTripSchema),
}

export const catalogDraftSchema = z.object({
  ...catalogBody,
  status: z.enum(['draft', 'validated']),
}).strict()

export const catalogVersionSchema = z.object({
  ...catalogBody,
  status: catalogStatusSchema,
  publishedAt: z.string().datetime().nullable(),
  publishedBy: z.string().min(1).nullable(),
}).strict()

export const catalogValidationIssueSchema = z.object({
  code: z.string().min(1),
  path: z.string().min(1),
  message: z.string().min(1),
  blocking: z.boolean(),
}).strict()

export type OperatorRole = z.infer<typeof operatorRoleSchema>
export type OperatorActor = z.infer<typeof operatorActorSchema>
export type CatalogDraft = z.infer<typeof catalogDraftSchema>
export type CatalogVersion = z.infer<typeof catalogVersionSchema>
export type CatalogValidationIssue = z.infer<typeof catalogValidationIssueSchema>
export type PublishedTrip = z.infer<typeof catalogTripSchema>
export type StopRole = z.infer<typeof stopRoleSchema>
export type RouteStop = z.infer<typeof routeStopSchema>
export type SeatClass = z.infer<typeof seatClassSchema>
export type VehicleTemplate = z.infer<typeof vehicleTemplateSchema>
export type VehicleTemplateSeat = z.infer<typeof vehicleTemplateSeatSchema>
export type FareRule = z.infer<typeof fareRuleSchema>
export type CatalogSchedule = z.infer<typeof catalogScheduleSchema>
