import { index, integer, jsonb, pgTable, serial, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

// ---------------------------------------------------------------------------
// Inventory — the real bus catalog. Seeded from an operator's own schedule (see
// docs/operator-data-format.md); nothing here is generated by the agent.
// ---------------------------------------------------------------------------

export const operators = pgTable('operators', {
  id: text('id').primaryKey(), // slug, e.g. 'phuong-trang'
  name: text('name').notNull(),
  hotline: text('hotline'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const routes = pgTable('routes', {
  id: text('id').primaryKey(), // e.g. 'sgn-dlt'
  operatorId: text('operator_id').notNull().references(() => operators.id),
  originCity: text('origin_city').notNull(),
  destinationCity: text('destination_city').notNull(),
  durationMinutes: integer('duration_minutes'),
  active: text('active', { enum: ['yes', 'no'] }).notNull().default('yes'),
}, (table) => [
  index('routes_origin_destination_idx').on(table.originCity, table.destinationCity),
])

export const trips = pgTable('trips', {
  id: text('id').primaryKey(), // e.g. 'sgn-dlt-2200-2026-07-25'
  routeId: text('route_id').notNull().references(() => routes.id),
  departureAt: timestamp('departure_at', { withTimezone: true }).notNull(),
  arrivalAt: timestamp('arrival_at', { withTimezone: true }),
  vehicleType: text('vehicle_type').notNull(),
  priceVnd: integer('price_vnd').notNull(),
  pickupPoint: text('pickup_point').notNull(),
  dropoffPoint: text('dropoff_point').notNull(),
  active: text('active', { enum: ['yes', 'no'] }).notNull().default('yes'),
}, (table) => [
  index('trips_route_departure_idx').on(table.routeId, table.departureAt),
])

// One row per physical seat. Holds live on the row itself so a single atomic
// UPDATE ... FOR UPDATE SKIP LOCKED can claim seats — two callers racing for the
// last seat can never both win.
export const seats = pgTable('seats', {
  id: serial('id').primaryKey(),
  tripId: text('trip_id').notNull().references(() => trips.id),
  code: text('code').notNull(), // 'A05'
  deck: text('deck', { enum: ['lower', 'upper'] }),
  status: text('status', { enum: ['available', 'held', 'booked'] }).notNull().default('available'),
  heldByCallId: text('held_by_call_id'),
  holdExpiresAt: timestamp('hold_expires_at', { withTimezone: true }),
  bookingId: integer('booking_id'),
}, (table) => [
  uniqueIndex('seats_trip_code_unique').on(table.tripId, table.code),
  index('seats_trip_status_idx').on(table.tripId, table.status),
])

export const bookings = pgTable('bookings', {
  id: serial('id').primaryKey(),
  code: text('code').notNull(), // 'VD-260725-0042'
  tripId: text('trip_id').notNull().references(() => trips.id),
  callId: text('call_id'),
  passengerName: text('passenger_name').notNull(),
  phone: text('phone').notNull(),
  seatCodes: jsonb('seat_codes').$type<string[]>().notNull(),
  totalFareVnd: integer('total_fare_vnd').notNull(),
  status: text('status', {
    enum: ['pending_payment', 'paid', 'cancelled'],
  }).notNull().default('pending_payment'),
  // Re-running the same confirmation (agent retry, duplicate turn) must return
  // the existing ticket instead of minting a second one.
  idempotencyKey: text('idempotency_key').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('bookings_code_unique').on(table.code),
  uniqueIndex('bookings_idempotency_unique').on(table.idempotencyKey),
])

export const payments = pgTable('payments', {
  id: serial('id').primaryKey(),
  bookingId: integer('booking_id').notNull().references(() => bookings.id),
  provider: text('provider').notNull(),
  amountVnd: integer('amount_vnd').notNull(),
  status: text('status', { enum: ['pending', 'succeeded', 'failed'] }).notNull().default('pending'),
  reference: text('reference'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('payments_provider_reference_unique').on(table.provider, table.reference),
])

export type OperatorRow = typeof operators.$inferSelect
export type RouteRow = typeof routes.$inferSelect
export type TripRow = typeof trips.$inferSelect
export type SeatRow = typeof seats.$inferSelect
export type BookingRow = typeof bookings.$inferSelect
export type PaymentRow = typeof payments.$inferSelect

// ---------------------------------------------------------------------------
// Call audit — a projection of what happened, never an input to the next turn.
// ---------------------------------------------------------------------------


// Final-only persistence: no partial transcripts, no raw audio. The booking core
// stays the source of truth — rows here are an audit/history projection of what
// already happened, never an input to the next turn.
export const calls = pgTable('calls', {
  id: text('id').primaryKey(), // = conversationId (room booking-<id>)
  channel: text('channel', { enum: ['phone', 'web'] }).notNull().default('web'),
  callerNumber: text('caller_number'),
  status: text('status', { enum: ['active', 'ended'] }).notNull().default('active'),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
  endedAt: timestamp('ended_at', { withTimezone: true }),
})

export const callTurns = pgTable('call_turns', {
  id: serial('id').primaryKey(),
  callId: text('call_id').notNull().references(() => calls.id),
  role: text('role', { enum: ['customer', 'agent'] }).notNull(),
  text: text('text').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const bookingSnapshots = pgTable('booking_snapshots', {
  id: serial('id').primaryKey(),
  callId: text('call_id').notNull().references(() => calls.id),
  snapshot: jsonb('snapshot').notNull(),
  status: text('status', {
    enum: ['collecting', 'trip_proposed', 'awaiting_confirmation', 'confirmed'],
  }).notNull(),
  bookingCode: text('booking_code'),
  totalFareVnd: integer('total_fare_vnd'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  // NULL booking codes stay distinct in Postgres, so interim snapshots insert
  // freely while a duplicate confirmed snapshot (same code) is rejected.
  uniqueIndex('booking_snapshots_call_code_unique').on(table.callId, table.bookingCode),
])

export type CallRow = typeof calls.$inferSelect
export type CallTurnRow = typeof callTurns.$inferSelect
export type BookingSnapshotRow = typeof bookingSnapshots.$inferSelect
