import { sql } from 'drizzle-orm'
import { bigint, boolean, check, index, integer, jsonb, pgTable, serial, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

// ---------------------------------------------------------------------------
// Inventory — the real bus catalog. Seeded from an operator's own schedule (see
// docs/operator-data-format.md); nothing here is generated by the agent.
// ---------------------------------------------------------------------------

export const operators = pgTable('operators', {
  id: text('id').primaryKey(), // slug, e.g. 'phuong-trang'
  name: text('name').notNull(),
  hotline: text('hotline'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const routes = pgTable('routes', {
  id: text('id').primaryKey(), // e.g. 'sgn-dlt'
  operatorId: text('operator_id').notNull().references(() => operators.id),
  originCity: text('origin_city').notNull(),
  destinationCity: text('destination_city').notNull(),
  durationMinutes: integer('duration_minutes'),
  active: text('active', { enum: ['yes', 'no'] }).notNull().default('yes'),
}, (table) => [
  index('routes_origin_destination_idx').on(table.originCity, table.destinationCity),
  check('routes_active_check', sql`${table.active} in ('yes', 'no')`),
  check('routes_duration_positive_check', sql`${table.durationMinutes} is null or ${table.durationMinutes} > 0`),
])

export const trips = pgTable('trips', {
  id: text('id').primaryKey(), // e.g. 'sgn-dlt-2200-2026-07-25'
  routeId: text('route_id').notNull().references(() => routes.id),
  departureAt: timestamp('departure_at', { withTimezone: true }).notNull(),
  arrivalAt: timestamp('arrival_at', { withTimezone: true }),
  vehicleType: text('vehicle_type').notNull(),
  priceVnd: integer('price_vnd').notNull(),
  pickupPoint: text('pickup_point').notNull(),
  dropoffPoint: text('dropoff_point').notNull(),
  active: text('active', { enum: ['yes', 'no'] }).notNull().default('yes'),
}, (table) => [
  index('trips_route_departure_idx').on(table.routeId, table.departureAt),
  check('trips_active_check', sql`${table.active} in ('yes', 'no')`),
  check('trips_price_positive_check', sql`${table.priceVnd} > 0`),
  check('trips_arrival_after_departure_check', sql`${table.arrivalAt} is null or ${table.arrivalAt} > ${table.departureAt}`),
])

export const bookings = pgTable('bookings', {
  id: serial('id').primaryKey(),
  code: text('code').notNull(), // 'MA-260725-0042'
  tripId: text('trip_id').notNull().references(() => trips.id),
  callId: text('call_id'),
  passengerName: text('passenger_name').notNull(),
  phone: text('phone').notNull(),
  confirmationText: text('confirmation_text').notNull(),
  seatCodes: jsonb('seat_codes').$type<string[]>().notNull(),
  totalFareVnd: integer('total_fare_vnd').notNull(),
  // Immutable facts captured in the authoritative confirmation statement.
  // Verification never rebuilds an old ticket from mutable trip/route rows.
  // This stays nullable for the expand side of the rolling migration. Legacy
  // rows without an archived confirmed snapshot are explicitly exempt rather
  // than being reconstructed from mutable route/trip data.
  verificationSnapshot: jsonb('verification_snapshot').$type<Record<string, unknown>>(),
  verificationSnapshotRequired: boolean('verification_snapshot_required').notNull().default(true),
  status: text('status', {
    enum: ['pending_payment', 'paid', 'cancelled'],
  }).notNull().default('pending_payment'),
  // Re-running the same confirmation (agent retry, duplicate turn) must return
  // the existing ticket instead of minting a second one.
  idempotencyKey: text('idempotency_key').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('bookings_code_unique').on(table.code),
  uniqueIndex('bookings_idempotency_unique').on(table.idempotencyKey),
  index('bookings_created_at_idx').on(table.createdAt),
  index('bookings_call_created_id_idx').on(table.callId, table.createdAt.desc(), table.id.desc()),
  check('bookings_status_check', sql`${table.status} in ('pending_payment', 'paid', 'cancelled')`),
  check('bookings_total_fare_nonnegative_check', sql`${table.totalFareVnd} >= 0`),
  check(
    'bookings_verification_snapshot_required_check',
    sql`not ${table.verificationSnapshotRequired} or ${table.verificationSnapshot} is not null`,
  ),
])

// One row per physical seat. Holds live on the row itself so a single atomic
// UPDATE ... FOR UPDATE SKIP LOCKED can claim seats — two callers racing for the
// last seat can never both win.
export const seats = pgTable('seats', {
  id: serial('id').primaryKey(),
  tripId: text('trip_id').notNull().references(() => trips.id),
  code: text('code').notNull(), // 'A05'
  deck: text('deck', { enum: ['lower', 'upper'] }),
  status: text('status', { enum: ['available', 'held', 'booked'] }).notNull().default('available'),
  heldByCallId: text('held_by_call_id'),
  holdExpiresAt: timestamp('hold_expires_at', { withTimezone: true }),
  bookingId: integer('booking_id').references(() => bookings.id),
}, (table) => [
  uniqueIndex('seats_trip_code_unique').on(table.tripId, table.code),
  index('seats_trip_status_idx').on(table.tripId, table.status),
  check('seats_deck_check', sql`${table.deck} is null or ${table.deck} in ('lower', 'upper')`),
  check('seats_status_check', sql`${table.status} in ('available', 'held', 'booked')`),
  check('seats_hold_shape_check', sql`
    (${table.status} = 'held' and ${table.heldByCallId} is not null and ${table.holdExpiresAt} is not null and ${table.bookingId} is null)
    or (${table.status} = 'booked' and ${table.bookingId} is not null and ${table.heldByCallId} is null and ${table.holdExpiresAt} is null)
    or (${table.status} = 'available' and ${table.bookingId} is null and ${table.heldByCallId} is null and ${table.holdExpiresAt} is null)
  `),
])

export const payments = pgTable('payments', {
  id: serial('id').primaryKey(),
  bookingId: integer('booking_id').notNull().references(() => bookings.id),
  provider: text('provider').notNull(),
  amountVnd: integer('amount_vnd').notNull(),
  status: text('status', { enum: ['pending', 'succeeded', 'failed'] }).notNull().default('pending'),
  reference: text('reference'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('payments_provider_reference_unique').on(table.provider, table.reference),
  check('payments_status_check', sql`${table.status} in ('pending', 'succeeded', 'failed')`),
  check('payments_amount_nonnegative_check', sql`${table.amountVnd} >= 0`),
])

export type OperatorRow = typeof operators.$inferSelect
export type RouteRow = typeof routes.$inferSelect
export type TripRow = typeof trips.$inferSelect
export type SeatRow = typeof seats.$inferSelect
export type BookingRow = typeof bookings.$inferSelect
export type PaymentRow = typeof payments.$inferSelect

// Public verification limits must survive serverless cold starts and apply
// across instances. Keys are HMAC digests; raw IPs, codes and phones are never
// persisted here.
export const publicRateLimits = pgTable('public_rate_limits', {
  key: text('key').primaryKey(),
  count: integer('count').notNull().default(0),
  resetsAt: timestamp('resets_at', { withTimezone: true }).notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('public_rate_limits_resets_at_idx').on(table.resetsAt),
  check('public_rate_limits_count_positive_check', sql`${table.count} > 0`),
])

// Enqueued in the same SQL statement that confirms a booking. The configured
// operator receiver deduplicates on event_id; state here prevents duplicate
// sends after an agent retry and leaves an auditable pending/failed record.
export const bookingWebhookOutbox = pgTable('booking_webhook_outbox', {
  eventId: text('event_id').primaryKey(),
  payload: jsonb('payload').notNull(),
  status: text('status', { enum: ['pending', 'delivering', 'delivered', 'failed'] }).notNull().default('pending'),
  attempts: integer('attempts').notNull().default(0),
  lastErrorCode: text('last_error_code'),
  lastAttemptAt: timestamp('last_attempt_at', { withTimezone: true }),
  nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }).notNull().defaultNow(),
  deliveredAt: timestamp('delivered_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('booking_webhook_outbox_status_created_idx').on(table.status, table.createdAt),
  check('booking_webhook_outbox_status_check', sql`${table.status} in ('pending', 'delivering', 'delivered', 'failed')`),
  check('booking_webhook_outbox_attempts_bounded_check', sql`${table.attempts} between 0 and 3`),
])

export type PublicRateLimitRow = typeof publicRateLimits.$inferSelect
export type BookingWebhookOutboxRow = typeof bookingWebhookOutbox.$inferSelect

// Explicit opt-ins from the public landing page. The email is retained only so
// Alove can deliver the requested product updates and can be deleted on request.
export const newsletterSubscriptions = pgTable('newsletter_subscriptions', {
  email: text('email').primaryKey(),
  source: text('source').notNull().default('landing_footer'),
  consentedAt: timestamp('consented_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check('newsletter_subscriptions_source_check', sql`${table.source} in ('landing_footer')`),
])

export type NewsletterSubscriptionRow = typeof newsletterSubscriptions.$inferSelect

// ---------------------------------------------------------------------------
// Call audit — a projection of what happened, never an input to the next turn.
// ---------------------------------------------------------------------------


// Final-only persistence: no partial transcripts, no raw audio. The booking core
// stays the source of truth — rows here are an audit/history projection of what
// already happened, never an input to the next turn.
export const calls = pgTable('calls', {
  id: text('id').primaryKey(), // = conversationId (room booking-<id>)
  channel: text('channel', { enum: ['phone', 'web'] }).notNull().default('web'),
  callerNumber: text('caller_number'),
  status: text('status', { enum: ['active', 'ended'] }).notNull().default('active'),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
  endedAt: timestamp('ended_at', { withTimezone: true }),
}, (table) => [
  check('calls_channel_check', sql`${table.channel} in ('phone', 'web')`),
  check('calls_status_check', sql`${table.status} in ('active', 'ended')`),
])

export const callTurns = pgTable('call_turns', {
  id: serial('id').primaryKey(),
  callId: text('call_id').notNull().references(() => calls.id),
  eventId: text('event_id').notNull(),
  sequence: bigint('sequence', { mode: 'number' }).notNull(),
  role: text('role', { enum: ['customer', 'agent'] }).notNull(),
  text: text('text').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('call_turns_call_event_unique').on(table.callId, table.eventId),
  uniqueIndex('call_turns_call_sequence_unique').on(table.callId, table.sequence),
  check('call_turns_role_check', sql`${table.role} in ('customer', 'agent')`),
  check('call_turns_sequence_positive_check', sql`${table.sequence} > 0`),
])

export const bookingSnapshots = pgTable('booking_snapshots', {
  id: serial('id').primaryKey(),
  callId: text('call_id').notNull().references(() => calls.id),
  eventId: text('event_id').notNull(),
  sequence: bigint('sequence', { mode: 'number' }).notNull(),
  snapshot: jsonb('snapshot').notNull(),
  status: text('status', {
    enum: ['collecting', 'trip_proposed', 'awaiting_confirmation', 'confirmed'],
  }).notNull(),
  bookingCode: text('booking_code'),
  totalFareVnd: integer('total_fare_vnd'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('booking_snapshots_call_event_unique').on(table.callId, table.eventId),
  uniqueIndex('booking_snapshots_call_sequence_unique').on(table.callId, table.sequence),
  check('booking_snapshots_status_check', sql`${table.status} in ('collecting', 'trip_proposed', 'awaiting_confirmation', 'confirmed')`),
  check('booking_snapshots_sequence_positive_check', sql`${table.sequence} > 0`),
])

export type CallRow = typeof calls.$inferSelect
export type CallTurnRow = typeof callTurns.$inferSelect
export type BookingSnapshotRow = typeof bookingSnapshots.$inferSelect
